[package]
name = "shadowbyte"
version = "2.0.0"
edition = "2024"
description = "A binary steganography engine in pure Rust."
authors = ["hihihehadika"]

[dependencies]
clap = { version = "4.6.0", features = ["derive"] }
image = { version = "0.25.10", default-features = false, features = ["png"] }
aes-gcm = "0.10"
argon2 = "0.5"
rand = "0.8"
rand_chacha = "0.3"
flate2 = "1.0"
reed-solomon-erasure = "6.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1"
getrandom = { version = "0.2", features = ["js"] }
instant = { version = "0.1", features = ["wasm-bindgen"] }

[lib]
name = "shadowbyte_core"
crate-type = ["cdylib", "rlib"]
